In [1]:
import pandas as pd
import numpy as np
import os

# 0. Cargar Datos

In [2]:
# Cargar precios lista
path_p_lista = "datos/Historial Precios Lista.xlsx"
precios_lista = pd.read_excel(path_p_lista, header=0)
precios_lista.head()

,Aplicación,Tipo de condición,Clase doc.ventas,Organización ventas,Canal distribución,Grupo precio cliente,Material,Descripción material,Fin de validez,Válido de,...,Canal Comercial,Grandes Cadenas,Status tratamiento,Importe,Moneda condición,UM de precio,Unidad de medida,Cantidad escala,Nombre de tabla,Descripción breve
0,V,ZP00,ZAIA,AGRO,NaN,NaN,9979802,ALMENDRA NON PAREIL,9999-12-31,2023-04-19,...,EX,NaN,NaN,7952300,CLP,10000,KG,0,A977,ClDocVenta/C.Comerc./Org.Ventas/Material
1,V,ZP00,ZAIA,AGRO,NaN,NaN,9979805,ALMENDRA CARMEL,9999-12-31,2023-04-19,...,EX,NaN,NaN,7952300,CLP,10000,KG,0,A977,ClDocVenta/C.Comerc./Org.Ventas/Material
2,V,ZP00,ZAIA,AGRO,NaN,NaN,9802,NARANJAS LANE LATE,9999-12-31,2025-08-27,...,OT,NaN,NaN,289200,CLP,10000,KG,0,A977,ClDocVenta/C.Comerc./Org.Ventas/Material
3,V,ZP00,ZAIA,AGRO,AG,NaN,9800,NARANJAS FUKUMOTO,9999-12-31,2025-08-27,...,NaN,NaN,NaN,1917800,CLP,10000,KG,0,A973,ClDocVenta/Org.Ventas/Can.distr./Material
4,V,ZP00,ZAIA,AGRO,AG,NaN,9801,NARANJAS WASHINTONG PARENT,2025-08-07,2025-08-01,...,NaN,NaN,NaN,495431,CLP,10000,KG,0,A973,ClDocVenta/Org.Ventas/Can.distr./Material

In [3]:
# Cargar info clientes
path_clientes = "datos/Base Datos Clientes - Carga de Trabajo.xlsx"
clientes = pd.read_excel(path_clientes, header=1)
clientes.head()

,Zona,Distrito,CodJV,CodSup,CodVend,NombreVendedor,Canal,SubCanal,CodCliente Padre,Cliente Padre,...,MA,MI,JU,VI,SA,Frecuencia,Tratamiento,CodPago,DesPago,Estado
0,SANTIAGO,SANTIAGO CENTRO COSTA,854,854,1084869,ALEXIS PEREZ MUÑOZ,COBERTURA,COBERTURA,0,-,...,0.0,0.0,0.0,1.0,0,1.0,Cliente,C005,FIRMA 7 DIAS,1
1,SUR 1,RANCAGUA,481,481,482,JUAN FARIAS PEREZ,COBERTURA,COBERTURA,0,-,...,0.0,0.0,0.0,0.0,0,0.5,Cliente,C000,EFECTIVO - CHEQUE AL DIA,1
2,SUR 2,CONCEPCION SUR,1178566,1178566,1084857,ALEX RIOS CUEVAS,COBERTURA,COBERTURA,0,-,...,0.0,0.0,0.5,0.0,0,0.5,Cliente,C017,EFECTIVO,1
3,SUR 1,TALCA,581,581,1160963,RODRIGO AVENDAÑO HERNANDEZ,COBERTURA,COBERTURA,0,-,...,0.0,1.0,0.0,0.0,0,1.0,Cliente,C044,PAGO ELECT CREDITO 07 DIAS,1
4,NORTE 2,VIÑA COSTA,1216438,1216438,1206012,PAULO RUZ BILBAO,COBERTURA,COBERTURA,0,-,...,1.0,0.0,0.0,1.0,0,2.0,Cliente,C044,PAGO ELECT CREDITO 07 DIAS,1

In [4]:
# Cargar datos de ventas
path_ventas = "datos/Ventas por Cliente/ventas_2025_2026.csv"
ventas = pd.read_csv(path_ventas)
ventas.head()

/var/folders/dw/9r647bwd1kl_g5lxtz0kh4100000gp/T/ipykernel_58237/3804140459.py:3: DtypeWarning: Columns (0: Cod Canal Comercial) have mixed types. Specify dtype option on import or set low_memory=False.
  ventas = pd.read_csv(path_ventas)

,Año,Mes,Cod Canal Comercial,Clase Factura,Fecha Factura,Cod Cliente,Nombre Cliente Padre,Cod Consolidado,Nombre Consolidado,Nombre Familia,...,Nombre Tipo Carne,Cod SKU,Nombre SKU,Factura Venta,Factura Kilos,Kilo Real,Kilos Nc,Monto Nc,Monto Real,Precio
0,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,SALAMES,...,CERDO,3034,SALAME 10x100 GR LP,43440,4.0,4.0,NaN,NaN,43440,10860.000000
1,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,MORTADELAS,...,CERDO,3049,MORTADELA JAMONADA LP 150 G.,17919,3.3,3.3,NaN,NaN,17919,5430.000000
2,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,PATE,...,CERDO,3080,PATE TEEWURST 16x125 GR LP,23888,4.0,4.0,NaN,NaN,23888,5972.000000
3,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,JAMON G1,...,CERDO,3108,JAMON PIERNA CP 8x250 GR LP,48869,6.0,6.0,NaN,NaN,48869,8144.833333
4,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,PATE,...,POLLO,3148,PASTA POLLO PIMENTON 8x125 GR LP,4887,1.0,1.0,NaN,NaN,4887,4887.000000

In [5]:
ventas.columns

Index(['Año', 'Mes', 'Cod Canal Comercial', 'Clase Factura', 'Fecha Factura',
       'Cod Cliente', 'Nombre Cliente Padre', 'Cod Consolidado',
       'Nombre Consolidado', 'Nombre Familia', 'N° Factura', 'Nombre Marca',
       'Nombre Tipo Carne', 'Cod SKU', 'Nombre SKU', 'Factura Venta',
       'Factura Kilos', 'Kilo Real', 'Kilos Nc', 'Monto Nc', 'Monto Real',
       'Precio'],
      dtype='str')

In [6]:
precios_lista.columns

Index(['Aplicación', 'Tipo de condición', 'Clase doc.ventas',
       'Organización ventas', 'Canal distribución', 'Grupo precio cliente',
       'Material', 'Descripción material', 'Fin de validez', 'Válido de',
       'Cliente', 'Tipo de Negocio', 'Canal Comercial', 'Grandes Cadenas',
       'Status tratamiento', 'Importe', 'Moneda condición', 'UM de precio',
       'Unidad de medida', 'Cantidad escala', 'Nombre de tabla',
       'Descripción breve'],
      dtype='str')

In [7]:
clientes.columns

Index(['Zona', 'Distrito', 'CodJV', 'CodSup', 'CodVend', 'NombreVendedor',
       'Canal', 'SubCanal', 'CodCliente Padre', 'Cliente Padre', 'CodCliente',
       'RazonSocial', 'Direccion', 'Comuna', 'TipoNeg', 'DesTipoNeg', 'Relev',
       'NivPrecio', 'Telefono', 'Correo', 'VtaUlt3M', 'PromUlt3M',
       'Margen3ULTM', 'PromMargen3ULTM', 'CodRuta', 'DesRuta', 'NroSec',
       'RitmoVisita', 'LU', 'MA', 'MI', 'JU', 'VI', 'SA', 'Frecuencia',
       'Tratamiento', 'CodPago', 'DesPago', 'Estado'],
      dtype='str')

In [8]:
# --- 1. Preparar tipos de dato ---
# Ajusta el formato de fecha según tu CSV (ej: '%d.%m.%Y', '%Y-%m-%d', etc.)
# En ventas está 20260106
date_fmt_ventas = '%Y%m%d'
# En precios lista está 2023-04-19
date_fmt_precios = '%Y-%m-%d'

ventas['Fecha Factura'] = pd.to_datetime(ventas['Fecha Factura'], format=date_fmt_ventas)
precios_lista['Válido de'] = pd.to_datetime(precios_lista['Válido de'], format=date_fmt_precios)
precios_lista['Fin de validez'] = pd.to_datetime(precios_lista['Fin de validez'], format=date_fmt_precios)

In [9]:
# Asegurar que las keys de join sean del mismo tipo
ventas = ventas.copy()
ventas['venta_id'] = ventas.index

ventas['Cod SKU'] = ventas['Cod SKU'].astype(str).str.strip()
ventas['Cod Canal Comercial'] = ventas['Cod Canal Comercial'].astype('string').str.strip()
ventas['Cod Cliente'] = ventas['Cod Cliente'].astype('string').str.strip()

def _normalize_consolidado_code(series):
    normalized = series.astype('string').str.strip().fillna('')
    return normalized.str.replace(r'\.0+$', '', regex=True)


ventas['Cod Consolidado'] = _normalize_consolidado_code(ventas['Cod Consolidado'])

def _blank_string_mask(series):
    return series.isna() | series.eq('')


def _fill_missing_canal_por_cliente(ventas_df):
    cliente = ventas_df['Cod Cliente']
    canal = ventas_df['Cod Canal Comercial']
    blank_mask = _blank_string_mask(canal)
    known_mask = (~blank_mask) & cliente.notna()

    vacios_originales = int(blank_mask.sum())

    if not known_mask.any():
        print('Cod Canal Comercial vacios originales: 0')
        print('Cod Canal Comercial imputados por cliente: 0')
        print('Cod Canal Comercial vacios restantes: 0')
        print('Clientes con conflicto de canal: 0')
        return ventas_df

    canales_por_cliente = canal.loc[known_mask].groupby(cliente.loc[known_mask], sort=False).nunique(dropna=True)
    clientes_conflictivos = canales_por_cliente[canales_por_cliente > 1].index

    lookup_mask = known_mask & ~cliente.isin(clientes_conflictivos)
    canal_lookup = canal.loc[lookup_mask].groupby(cliente.loc[lookup_mask], sort=False).first()

    fill_values = cliente.loc[blank_mask].map(canal_lookup)
    imputadas = int(fill_values.notna().sum())
    ventas_df.loc[blank_mask, 'Cod Canal Comercial'] = fill_values

    vacios_restantes = int(_blank_string_mask(ventas_df['Cod Canal Comercial']).sum())

    print(f'Cod Canal Comercial vacios originales: {vacios_originales:,}')
    print(f'Cod Canal Comercial imputados por cliente: {imputadas:,}')
    print(f'Cod Canal Comercial vacios restantes: {vacios_restantes:,}')
    print(f'Clientes con conflicto de canal: {len(clientes_conflictivos):,}')

    if len(clientes_conflictivos):
        conflict_mask = known_mask & cliente.isin(clientes_conflictivos)
        ejemplos_conflicto = (
            canal.loc[conflict_mask]
            .groupby(cliente.loc[conflict_mask], sort=False)
            .agg(lambda s: sorted(pd.unique(s).tolist()))
            .head(10)
            .to_dict()
        )
        print('Ejemplos de clientes conflictivos:', ejemplos_conflicto)

    return ventas_df


ventas = _fill_missing_canal_por_cliente(ventas)

clientes_lookup = clientes[['CodCliente', 'Zona', 'Distrito']].copy()
clientes_lookup['CodCliente'] = clientes_lookup['CodCliente'].astype('string').str.strip()
clientes_lookup['Zona'] = clientes_lookup['Zona'].astype('string').str.strip()
clientes_lookup['Distrito'] = clientes_lookup['Distrito'].astype('string').str.strip()
clientes_lookup = clientes_lookup[clientes_lookup['CodCliente'].notna()].copy()

ventas = ventas.merge(
    clientes_lookup.rename(columns={'CodCliente': 'Cod Cliente'}),
    on='Cod Cliente',
    how='left',
    validate='m:1',
)

precios_lista['Material'] = precios_lista['Material'].astype(str).str.strip()
precios_lista['Canal Comercial'] = precios_lista['Canal Comercial'].astype(str).str.strip()
precios_lista['Grandes Cadenas'] = _normalize_consolidado_code(precios_lista['Grandes Cadenas'])
precios_lista['org_ventas_norm'] = (
    precios_lista['Organización ventas']
    .astype('string')
    .str.strip()
    .fillna('')
)
precios_lista = precios_lista[precios_lista['org_ventas_norm'].isin(['', 'PASJ', 'CYSJ'])].copy()

Cod Canal Comercial vacios originales: 729,985
Cod Canal Comercial imputados por cliente: 729,771
Cod Canal Comercial vacios restantes: 214
Clientes con conflicto de canal: 0

# 1. Agregar a cada transacción su precio lista

In [10]:
# --- 2. Versión low memory (SKU + canal + org + cod consolidado) ---
# Evita cruces cartesianos: recorre grupos de precios por organización y
# asigna primero por cod consolidado, usando Grandes Cadenas en blanco como fallback.
def _assign_prices_from_org(out, sales_indices, price_groups, sales_org):
    for key_values, price_rows in price_groups.items():
        if not isinstance(key_values, tuple):
            key_values = (key_values,)

        sales_idx = sales_indices.get(tuple(key_values) + (sales_org,))
        if sales_idx is None or len(sales_idx) == 0:
            continue

        fechas = out.loc[sales_idx, 'Fecha Factura']
        pendientes = out.loc[sales_idx, 'Precio_Lista'].isna()

        for valido_desde, valido_hasta, importe, _ in price_rows.itertuples(index=False, name=None):
            mask = pendientes & fechas.ge(valido_desde) & fechas.le(valido_hasta)
            if mask.any():
                out.loc[mask.index[mask], 'Precio_Lista'] = importe
                pendientes = out.loc[sales_idx, 'Precio_Lista'].isna()
                if not pendientes.any():
                    break


def _build_price_groups(precios_df, org_value):
    prices = precios_df.loc[precios_df['org_ventas_norm'].eq(org_value)].copy()

    exact_prices = prices.loc[prices['Grandes Cadenas'].ne('')].copy()
    fallback_prices = prices.loc[prices['Grandes Cadenas'].eq('')].copy()

    exact_groups = {
        key: (
            sub[['Válido de', 'Fin de validez', 'Importe', '__source_order']]
            .sort_values(['Válido de', '__source_order'], ascending=[False, True])
            .reset_index(drop=True)
        )
        for key, sub in exact_prices.groupby(['Material', 'Canal Comercial', 'Grandes Cadenas'], sort=False, dropna=False)
    }
    fallback_groups = {
        key: (
            sub[['Válido de', 'Fin de validez', 'Importe', '__source_order']]
            .sort_values(['Válido de', '__source_order'], ascending=[False, True])
            .reset_index(drop=True)
        )
        for key, sub in fallback_prices.groupby(['Material', 'Canal Comercial'], sort=False, dropna=False)
    }

    return {
        'exact': exact_groups,
        'fallback': fallback_groups,
    }


def _assign_price_list_low_memory(ventas_df, precios_df):
    out = ventas_df.copy()
    out['Precio_Lista'] = np.nan
    out['org_target'] = out['Distrito'].map({
        'COYHAIQUE': 'CYSJ',
        'PUNTA ARENAS': 'PASJ',
    }).fillna('')

    sales_indices_exact = out.groupby(['Cod SKU', 'Cod Canal Comercial', 'Cod Consolidado', 'org_target'], sort=False, dropna=False).indices
    sales_indices_fallback = out.groupby(['Cod SKU', 'Cod Canal Comercial', 'org_target'], sort=False, dropna=False).indices

    precios_work = precios_df.copy()
    precios_work['__source_order'] = np.arange(len(precios_work))

    price_groups_by_org = {
        org: _build_price_groups(precios_work, org)
        for org in ['CYSJ', 'PASJ', '']
    }

    _assign_prices_from_org(out, sales_indices_exact, price_groups_by_org['CYSJ']['exact'], 'CYSJ')
    _assign_prices_from_org(out, sales_indices_fallback, price_groups_by_org['CYSJ']['fallback'], 'CYSJ')
    _assign_prices_from_org(out, sales_indices_exact, price_groups_by_org['PASJ']['exact'], 'PASJ')
    _assign_prices_from_org(out, sales_indices_fallback, price_groups_by_org['PASJ']['fallback'], 'PASJ')

    for sales_org in ['CYSJ', 'PASJ', '']:
        _assign_prices_from_org(out, sales_indices_exact, price_groups_by_org['']['exact'], sales_org)
        _assign_prices_from_org(out, sales_indices_fallback, price_groups_by_org['']['fallback'], sales_org)

    return out.drop(columns=['org_target'])


merged = _assign_price_list_low_memory(ventas, precios_lista)

In [11]:
# --- Métricas finales ---
matched_ids = set(merged.loc[merged['Precio_Lista'].notna(), 'venta_id'])

print(f"Ventas originales: {len(ventas):,}")
print(f"Con precio lista asignado: {len(matched_ids):,}")
print(f"Sin match: {len(ventas) - len(matched_ids):,}")

Ventas originales: 10,596,574
Con precio lista asignado: 10,595,574
Sin match: 1,000

In [12]:
# ver filas sin match:
sin_match = ventas[~ventas['venta_id'].isin(matched_ids)].drop(columns=['venta_id'])
sin_match.head()

,Año,Mes,Cod Canal Comercial,Clase Factura,Fecha Factura,Cod Cliente,Nombre Cliente Padre,Cod Consolidado,Nombre Consolidado,Nombre Familia,...,Nombre SKU,Factura Venta,Factura Kilos,Kilo Real,Kilos Nc,Monto Nc,Monto Real,Precio,Zona,Distrito
8487,2025,1,CB,ZV01,2025-01-02,1134628,NaN,32,COBERTURA,HAMBURGUESAS,...,HAMBURGUESA GRILL TASTE LP 100 G.,14772,4.0,4.0,NaN,NaN,14772,3693.000000,SUR 1,SAN FERNANDO
26541,2025,1,MY,ZV01,2025-01-03,52847,COMERCIAL DOLLINCO S.A.,57,MAYORISTA B VOLUMEN,SALAMES,...,PEPPERONI LP 9X500 G.,4974750,742.5,742.5,NaN,NaN,4974750,6700.000000,SANTIAGO,SANTIAGO MAYORISTA
35111,2025,1,MY,ZV01,2025-01-03,1070919,COMERCIAL GALVARINO LIMITADA,57,MAYORISTA B VOLUMEN,VIENESAS,...,SALCHICHA SUREÑA REDUCIDA EN SODIO 500 G,690288,292.0,292.0,NaN,NaN,690288,2364.000000,SANTIAGO,SANTIAGO MAYORISTA
35118,2025,1,MY,ZV01,2025-01-03,1070919,COMERCIAL GALVARINO LIMITADA,57,MAYORISTA B VOLUMEN,SALAMES,...,PEPPERONI LP 9X500 G.,149594,13.5,13.5,NaN,NaN,149594,11081.037037,SANTIAGO,SANTIAGO MAYORISTA
68387,2025,1,CB,ZV01,2025-01-06,1228271,NaN,54,VOLUMEN COBERTURA,HAMBURGUESAS,...,HAMBURGUESA GRILL TASTE LP 100 G.,29548,4.0,4.0,NaN,NaN,29548,7387.000000,SUR 2,CHILLAN

In [13]:
# Ver precio lista para 2026-01-06 del sku 3239 en canal CB y cod consolidado 32,
# incluyendo fallback a Grandes Cadenas en blanco:
precios_lista[(precios_lista['Material'] == '3239') & 
              (precios_lista['Canal Comercial'] == 'CB') & 
              (precios_lista['Grandes Cadenas'].isin(['32', ''])) & 
              (precios_lista['Válido de'] <= '2026-01-06') & 
              (precios_lista['Fin de validez'] >= '2026-01-06')][
    ['Material', 'Canal Comercial', 'Grandes Cadenas', 'Organización ventas', 'Válido de', 'Fin de validez', 'Importe']
].sort_values(['Grandes Cadenas', 'Organización ventas', 'Válido de'])

,Material,Canal Comercial,Grandes Cadenas,Organización ventas,Válido de,Fin de validez,Importe
6207,3239,CB,,CYSJ,2025-04-14,9999-12-31,7602
6978,3239,CB,,PASJ,2025-04-14,9999-12-31,7602
10748,3239,CB,,NaN,2025-04-14,9999-12-31,7240

In [14]:
# Diagnóstico rápido de sin_match
print('Sin match por combinación SKU+canal+cod consolidado:')
print(sin_match.groupby(['Cod SKU', 'Cod Canal Comercial', 'Cod Consolidado']).size().sort_values(ascending=False))

# Ejemplo: revisar esos SKU en catálogo de precios, incluyendo Grandes Cadenas
skus_sin_match = sin_match['Cod SKU'].drop_duplicates().tolist()
precios_lista[precios_lista['Material'].isin(skus_sin_match)][
    ['Material', 'Canal Comercial', 'Grandes Cadenas', 'Canal distribución', 'Organización ventas', 'Válido de', 'Fin de validez', 'Importe']
].sort_values(['Material', 'Canal Comercial', 'Grandes Cadenas', 'Organización ventas', 'Válido de'])

Sin match por combinación SKU+canal+cod consolidado:
Cod SKU  Cod Canal Comercial  Cod Consolidado
3752     HR                   56                 455
3754     HR                   56                 367
3661     HR                   55                  51
3988     HR                   56                  27
3660     MY                   57                  26
3657     HR                   37                  13
3661     HR                   37                   9
3995     MY                   57                   8
3990     MY                   57                   4
3661     CB                   32                   4
677      CB                   54                   4
                              32                   4
3661     MY                   57                   3
3995     CB                   32                   3
677      MY                   38                   3
3657     CB                   32                   3
3050     MY                   57                   2
3998     MY                   57                   2
3995     MY                   38                   2
3990     HR                   37                   2
1036     MY                   57                   1
3988     CB                   32                   1
         MY                   57                   1
         CB                   54                   1
3752     HR                   37                   1
3661     CB                   54                   1
3657     CB                   54                   1
677      MY                   57                   1
dtype: int64

,Material,Canal Comercial,Grandes Cadenas,Canal distribución,Organización ventas,Válido de,Fin de validez,Importe
18338,1036,NaN,,NaN,NaN,2019-09-11,9999-12-31,1152
6128,3050,CB,,NaN,CYSJ,2025-05-12,2025-06-01,13032
6129,3050,CB,,NaN,CYSJ,2025-06-02,2025-06-08,14117
6130,3050,CB,,NaN,CYSJ,2025-06-09,9999-12-31,15204
6899,3050,CB,,NaN,PASJ,2025-05-12,2025-06-01,13032
...,...,...,...,...,...,...,...,...
13633,677,NaN,,SV,NaN,2025-09-02,2025-09-30,6149
13634,677,NaN,,SV,NaN,2025-10-01,2025-12-31,6149
13635,677,NaN,,SV,NaN,2026-01-01,2026-02-28,6149
13636,677,NaN,,SV,NaN,2026-03-01,2026-03-31,6149
13637,677,NaN,,SV,NaN,2026-04-01,9999-12-31,6149

In [15]:
# guardar ventas con precio lista asignado
# output_path = "datos/Ventas por Cliente/preliminar_ventas_con_precio_lista_2025_2026.csv"
# merged.to_csv(output_path, index=False)
# print(f"Archivo guardado en: {output_path}")

In [16]:
merged.columns

Index(['Año', 'Mes', 'Cod Canal Comercial', 'Clase Factura', 'Fecha Factura',
       'Cod Cliente', 'Nombre Cliente Padre', 'Cod Consolidado',
       'Nombre Consolidado', 'Nombre Familia', 'N° Factura', 'Nombre Marca',
       'Nombre Tipo Carne', 'Cod SKU', 'Nombre SKU', 'Factura Venta',
       'Factura Kilos', 'Kilo Real', 'Kilos Nc', 'Monto Nc', 'Monto Real',
       'Precio', 'venta_id', 'Zona', 'Distrito', 'Precio_Lista'],
      dtype='str')

# 2. Agregar a cada transacción sus descuentos posibles

In [17]:
path_dscto_base = "datos/Descuentos históricos/dscto_base.xlsx"
dsctos_base = pd.read_excel(path_dscto_base, header=0)
dsctos_base.head()

,Unnamed: 0,Aplicación,Tipo cond.,Cl.doc.vt.,Org.ventas,Can.distr.,Gr.precios,Material,Descripción material,A,...,C.Comerc.,G.Cadenas,Stat.trat.,Importe,Mon.cond.,Unidad,UM,Ctd.escala,Tabla,Descripción breve
0,NaN,V,ZDBA,,ANSJ,,,3071,PATE TERNERA 160 Gr.(x10),08.06.2024,...,CB,32,,-15.0,%,0,,,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
1,NaN,V,ZDBA,,ARSJ,,,3071,PATE TERNERA 160 Gr.(x10),08.06.2024,...,CB,32,,-15.0,%,0,,,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
2,NaN,V,ZDBA,,CHSJ,,,915,VIENESA SUREÑA 12x250 GR SJ,29.02.2024,...,CB,32,,-10.0,%,0,,,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
3,NaN,V,ZDBA,,CHSJ,,,3071,PATE TERNERA 160 Gr.(x10),08.06.2024,...,CB,32,,-15.0,%,0,,,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
4,NaN,V,ZDBA,,CLSJ,,,3071,PATE TERNERA 160 Gr.(x10),08.06.2024,...,CB,32,,-15.0,%,0,,,A978,C.Comerc./G.Cadenas/Org.Ventas/Material

In [18]:
print(dsctos_base.columns)
print(dsctos_base.shape)

Index(['Unnamed: 0', 'Aplicación', 'Tipo cond.', 'Cl.doc.vt.', 'Org.ventas',
       'Can.distr.', 'Gr.precios', 'Material',
       'Descripción material                    ', 'A         ', 'Válido de ',
       'Cliente', 'Tipo.N', 'C.Comerc.', 'G.Cadenas', 'Stat.trat.', 'Importe',
       'Mon.cond.', 'Unidad', 'UM', 'Ctd.escala', 'Tabla',
       'Descripción breve                       '],
      dtype='str')
(3644, 23)

In [19]:
cols_dscto_base = [
    # SKU
    "Material",
    # Canal Comercial (se conserva como referencia)
    "C.Comerc.",
    # Código consolidado / Grandes Cadenas
    "G.Cadenas",
    # Tipo de descuento
    "Tipo cond.",
    # Fechas de duración del descuento
    "Válido de ",
    "A         ",
    # Monto o porcentaje de descuento
    "Importe"
]
dsctos_base = dsctos_base[cols_dscto_base]
dsctos_base.head()

   Material  C.Comerc. G.Cadenas  Tipo cond.  Válido de   A           Importe
0      3071  CB               32  ZDBA        27.05.2024  08.06.2024    -15.0
1      3071  CB               32  ZDBA        27.05.2024  08.06.2024    -15.0
2       915  CB               32  ZDBA        05.02.2024  29.02.2024    -10.0
3      3071  CB               32  ZDBA        27.05.2024  08.06.2024    -15.0
4      3071  CB               32  ZDBA        27.05.2024  08.06.2024    -15.0

In [20]:
path_dscto_volumen = "datos/Descuentos históricos/dscto_volumen.xlsx"
dsctos_volumen = pd.read_excel(path_dscto_volumen, header=0)
dsctos_volumen.head()

,Unnamed: 0,Aplicación,Tipo cond.,Cl.doc.vt.,Org.ventas,Can.distr.,Gr.precios,Material,Descripción material,A,...,C.Comerc.,G.Cadenas,Stat.trat.,Importe,Mon.cond.,Unidad,UM,Ctd.escala,Tabla,Descripción breve
0,NaN,V,ZDVL,,SGSJ,,,3071,PATE TERNERA 160 Gr.(x10),08.06.2024,...,CB,32,,"15,00-",%,0,,2,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
1,NaN,V,ZDVL,,SGSJ,,,3456,"SALAME LAMINADO 1,6 KG LP",29.02.2024,...,CB,32,,"10,00-",%,0,,4,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
2,NaN,V,ZDVL,,SGSJ,,,3071,PATE TERNERA 160 Gr.(x10),08.06.2024,...,CB,54,,"15,00-",%,0,,2,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
3,NaN,V,ZDVL,,SGSJ,,,3456,"SALAME LAMINADO 1,6 KG LP",29.02.2024,...,CB,54,,"10,00-",%,0,,4,A978,C.Comerc./G.Cadenas/Org.Ventas/Material
4,NaN,V,ZDVL,,ANSJ,,,6770,QUESO GAUDA LAMINADO 1KG.LOS NOGALES,25.04.2024,...,MY,57,,"21,20-",%,0,,54,A978,C.Comerc./G.Cadenas/Org.Ventas/Material

In [21]:
print(dsctos_volumen.columns)
print(dsctos_volumen.shape)

Index(['Unnamed: 0', 'Aplicación', 'Tipo cond.', 'Cl.doc.vt.', 'Org.ventas',
       'Can.distr.', 'Gr.precios', 'Material',
       'Descripción material                    ', 'A         ', 'Válido de ',
       'Cliente', 'Tipo.N', 'C.Comerc.', 'G.Cadenas', 'Stat.trat.', 'Importe',
       'Mon.cond.', 'Unidad', 'UM', 'Ctd.escala', 'Tabla',
       'Descripción breve                      '],
      dtype='str')
(2181, 23)

In [22]:
cols_dscto_volumen = [
    # SKU
    "Material",
    # Canal Comercial (se conserva como referencia)
    "C.Comerc.",
    # Código consolidado / Grandes Cadenas
    "G.Cadenas",
    # Tipo de descuento
    "Tipo cond.",
    # Fechas de duración del descuento
    "Válido de ",
    "A         ",
    # Monto o porcentaje de descuento
    "Importe"
]
dsctos_volumen = dsctos_volumen[cols_dscto_volumen]
dsctos_volumen.head()

   Material  C.Comerc. G.Cadenas  Tipo cond.  Válido de   A           Importe
0      3071  CB               32  ZDVL        27.05.2024  08.06.2024   15,00-
1      3456  CB               32  ZDVL        07.02.2024  29.02.2024   10,00-
2      3071  CB               54  ZDVL        27.05.2024  08.06.2024   15,00-
3      3456  CB               54  ZDVL        07.02.2024  29.02.2024   10,00-
4      6770  MY               57  ZDVL        16.04.2024  25.04.2024   21,20-

In [23]:
path_dscto_binario = "datos/Descuentos históricos/dscto_binario.xlsx"
dsctos_binario = pd.read_excel(path_dscto_binario, header=0)
dsctos_binario.head()

,Unnamed: 0,Aplicación,Tipo cond.,Cl.doc.vt.,Org.ventas,Can.distr.,Gr.precios,Material,Descripción material,A,...,C.Comerc.,G.Cadenas,Stat.trat.,Importe,Mon.cond.,Unidad,UM,Ctd.escala,Tabla,Descripción breve
0,NaN,V,ZDVE,,SGSJ,,,3982,PEPPERONI HORECA LP BOLSA 4 X 500G.,01.12.2025,...,CB,32,,"5,00-",%,0,,,A979,C.Comerc./G.Cadenas/Tipo.N/Org.Ventas/Material
1,NaN,V,ZDVE,,SGSJ,,,3982,PEPPERONI HORECA LP BOLSA 4 X 500G.,01.12.2025,...,CB,54,,"5,00-",%,0,,,A979,C.Comerc./G.Cadenas/Tipo.N/Org.Ventas/Material
2,NaN,V,ZDVE,,,,,20,ARROLLADO LOMO CON AJI SJ,28.02.2026,...,CB,32,,"15,00-",%,0,,,A953,C.Comerc./G.Cadenas/Material
3,NaN,V,ZDVE,,,,,27,ARROLLADO LOMO SIN AJI SJ,28.02.2026,...,CB,32,,"15,00-",%,0,,,A953,C.Comerc./G.Cadenas/Material
4,NaN,V,ZDVE,,,,,30,ARROLLADO HUASO CON AJI SJ,28.02.2026,...,CB,32,,"15,00-",%,0,,,A953,C.Comerc./G.Cadenas/Material

In [24]:
print(dsctos_binario.columns)
print(dsctos_binario.shape)

Index(['Unnamed: 0', 'Aplicación', 'Tipo cond.', 'Cl.doc.vt.', 'Org.ventas',
       'Can.distr.', 'Gr.precios', 'Material',
       'Descripción material                    ', 'A         ', 'Válido de ',
       'Cliente', 'Tipo.N', 'C.Comerc.', 'G.Cadenas', 'Stat.trat.', 'Importe',
       'Mon.cond.', 'Unidad', 'UM', 'Ctd.escala', 'Tabla',
       'Descripción breve                             '],
      dtype='str')
(1310, 23)

In [25]:
cols_dscto_binario = [
    # SKU
    "Material",
    # Canal Comercial (se conserva como referencia)
    "C.Comerc.",
    # Código consolidado / Grandes Cadenas
    "G.Cadenas",
    # Tipo de descuento
    "Tipo cond.",
    # Fechas de duración del descuento
    "Válido de ",
    "A         ",   
    # Monto o porcentaje de descuento
    "Importe"
]
dsctos_binario = dsctos_binario[cols_dscto_binario]
dsctos_binario.head()

   Material  C.Comerc.  G.Cadenas  Tipo cond.  Válido de   A           Importe
0      3982  CB                32  ZDVE        01.12.2025  01.12.2025    5,00-
1      3982  CB                54  ZDVE        01.12.2025  01.12.2025    5,00-
2        20  CB                32  ZDVE        02.02.2026  28.02.2026   15,00-
3        27  CB                32  ZDVE        02.02.2026  28.02.2026   15,00-
4        30  CB                32  ZDVE        02.02.2026  28.02.2026   15,00-

In [26]:
# Juntamos los dsctos en una sola base para facilitar su uso posterior:
dsctos = pd.concat([dsctos_base, dsctos_volumen, dsctos_binario], ignore_index=True)
dsctos.head()

   Material  C.Comerc. G.Cadenas  Tipo cond.  Válido de   A          Importe
0      3071  CB               32  ZDBA        27.05.2024  08.06.2024   -15.0
1      3071  CB               32  ZDBA        27.05.2024  08.06.2024   -15.0
2       915  CB               32  ZDBA        05.02.2024  29.02.2024   -10.0
3      3071  CB               32  ZDBA        27.05.2024  08.06.2024   -15.0
4      3071  CB               32  ZDBA        27.05.2024  08.06.2024   -15.0

In [27]:
# dscto carta_impacto
path_carta_impacto = "datos/Descuentos históricos/carta_impacto.xlsx"
carta_impacto = pd.read_excel(path_carta_impacto, header=0)
carta_impacto.head()

,Unnamed: 0,Aplicación,Tipo cond.,Cl.doc.vt.,Org.ventas,Can.distr.,Gr.precios,Material,Descripción material,A,...,C.Comerc.,G.Cadenas,Stat.trat.,Importe,Mon.cond.,Unidad,UM,Ctd.escala,Tabla,Descripción breve
0,NaN,V,ZCAI,,,CB,,710,HAMBURGUESA 24x90 GR SJ,31.05.2025,...,,,ZL,3878,CLP,1,KG,0,A946,Can.distr./Cliente/Material/Liber
1,NaN,V,ZCAI,,,CB,,1350,JAMON ACARAMELADO SJ,31.05.2025,...,,,ZL,6051,CLP,1,KG,0,A946,Can.distr./Cliente/Material/Liber
2,NaN,V,ZCAI,,,CB,,1372,JAMON COLONIAL MINI PZA SJ,31.05.2025,...,,,ZL,6051,CLP,1,KG,0,A946,Can.distr./Cliente/Material/Liber
3,NaN,V,ZCAI,,,CB,,1433,CHORIZO PARRILLERO SJ 800 G.,31.05.2025,...,,,ZL,3055,CLP,1,KG,0,A946,Can.distr./Cliente/Material/Liber
4,NaN,V,ZCAI,,,CB,,1446,LONGANIZA SJ 800 GR.,31.05.2025,...,,,ZL,3055,CLP,1,KG,0,A946,Can.distr./Cliente/Material/Liber

In [28]:
print(carta_impacto.columns)
print(carta_impacto.shape)

Index(['Unnamed: 0', 'Aplicación', 'Tipo cond.', 'Cl.doc.vt.', 'Org.ventas',
       'Can.distr.', 'Gr.precios', 'Material',
       'Descripción material                    ', 'A         ', 'Válido de ',
       'Cliente', 'Tipo.N', 'C.Comerc.', 'G.Cadenas', 'Stat.trat.', 'Importe',
       'Mon.cond.', 'Unidad', 'UM', 'Ctd.escala', 'Tabla',
       'Descripción breve                '],
      dtype='str')
(69438, 23)

In [29]:
cols_carta_impacto = [
    # SKU
    "Material",
    # Cliente
    "Cliente",
    # Tipo de descuento
    "Tipo cond.",
    # Fechas de duración del descuento
    "Válido de ",
    "A         ",   
    # Monto o porcentaje de descuento
    "Importe"
]
carta_impacto = carta_impacto[cols_carta_impacto]
carta_impacto.head()

   Material  Cliente  Tipo cond.  Válido de   A           Importe
0       710    15003  ZCAI        01.05.2025  31.05.2025     3878
1      1350    15003  ZCAI        01.05.2025  31.05.2025     6051
2      1372    15003  ZCAI        01.05.2025  31.05.2025     6051
3      1433    15003  ZCAI        01.05.2025  31.05.2025     3055
4      1446    15003  ZCAI        01.05.2025  31.05.2025     3055

In [30]:
# Agregar a base de ventas por transacción:
#     - columnas de monto e id para descuentos base, volumen, binario y carta impacto
#     - tabla consolidada de descuentos con todas las reglas posibles
#     - para base/volumen/binario: match exacto por sku+canal+consolidado y fallback por sku+canal


def _as_stripped(series):
    return series.astype("string").str.strip()


def _normalize_consolidado_key(series):
    normalized = series.astype("string").str.strip().fillna("")
    return normalized.str.replace(r"\.0+$", "", regex=True)


def _parse_signed_discount(series):
    cleaned = series.astype("string").str.strip()
    negative_mask = cleaned.str.endswith("-") | cleaned.str.startswith("-")
    cleaned = cleaned.str.replace("-", "", regex=False)
    cleaned = cleaned.str.replace(".", "", regex=False)
    cleaned = cleaned.str.replace(",", ".", regex=False)
    values = pd.to_numeric(cleaned, errors="coerce")
    return values.where(~negative_mask, -values.abs())


def _prepare_discount_frame(df, required_cols, importe_parser, tipo_descuento, rename_map, blank_allowed_cols=None):
    out = df.copy()
    blank_allowed_cols = set(blank_allowed_cols or [])

    for source_col in rename_map:
        if source_col not in out.columns or source_col in ["Válido de ", "A         ", "Importe"]:
            continue

        if source_col == "G.Cadenas":
            out[source_col] = _normalize_consolidado_key(out[source_col])
        else:
            out[source_col] = _as_stripped(out[source_col])

        if source_col in required_cols:
            out = out[out[source_col].notna() & out[source_col].ne("")]
        elif source_col not in blank_allowed_cols:
            out = out[out[source_col].notna() & out[source_col].ne("")]

    out["Válido de "] = pd.to_datetime(out["Válido de "], format="%d.%m.%Y", errors="coerce")
    out["A         "] = pd.to_datetime(out["A         "], format="%d.%m.%Y", errors="coerce")
    out["Importe"] = importe_parser(out["Importe"])
    out["__source_order"] = np.arange(len(out))

    out = out.dropna(subset=required_cols + ["Válido de ", "A         ", "Importe"]).copy()
    out = out.rename(columns=rename_map)

    for col in ["cod_sku", "cod_canal", "cod_consolidado", "cod_cliente"]:
        if col not in out.columns:
            out[col] = pd.NA

    if "cod_sku" in out.columns:
        out["cod_sku"] = _as_stripped(out["cod_sku"])
    if "cod_canal" in out.columns:
        out["cod_canal"] = _as_stripped(out["cod_canal"])
    if "cod_cliente" in out.columns:
        out["cod_cliente"] = _as_stripped(out["cod_cliente"])
    if "cod_consolidado" in out.columns:
        out["cod_consolidado"] = _normalize_consolidado_key(out["cod_consolidado"])

    out["tipo_descuento"] = tipo_descuento

    cols_publicos = [
        "tipo_descuento",
        "cod_sku",
        "cod_canal",
        "cod_consolidado",
        "cod_cliente",
        "fecha_inicio",
        "fecha_fin",
        "monto_descuento",
    ]

    out = (
        out[cols_publicos + ["__source_order"]]
        .drop_duplicates(subset=cols_publicos, keep="first")
        .reset_index(drop=True)
    )

    return out


def _assign_single_discount(ventas_df, descuentos_df, sales_keys, discount_keys, output_col, output_id_col):
    out = ventas_df.copy()
    if output_col not in out.columns:
        out[output_col] = pd.NA
    if output_id_col not in out.columns:
        out[output_id_col] = pd.NA

    lookup = {
        key: sub[["id_descuento", "fecha_inicio", "fecha_fin", "monto_descuento", "__source_order"]].reset_index(drop=True)
        for key, sub in descuentos_df.groupby(discount_keys, sort=False, dropna=False)
    }

    chunks = []
    for key_values, grupo in out.groupby(sales_keys, sort=False, dropna=False):
        if not isinstance(key_values, tuple):
            key_values = (key_values,)

        grupo = grupo.copy()
        grupo["__row_id_tmp"] = grupo.index
        pendientes = grupo[output_col].isna()
        if not pendientes.any():
            chunks.append(grupo.drop(columns=["__row_id_tmp"]))
            continue

        descuentos_sub = lookup.get(tuple(key_values))
        if descuentos_sub is None or descuentos_sub.empty:
            chunks.append(grupo.drop(columns=["__row_id_tmp"]))
            continue

        tmp = grupo.loc[pendientes, ["__row_id_tmp", "Fecha Factura"]].merge(descuentos_sub, how="cross")
        tmp_valid = tmp[
            (tmp["Fecha Factura"] >= tmp["fecha_inicio"]) &
            (tmp["Fecha Factura"] <= tmp["fecha_fin"])
        ]

        if tmp_valid.empty:
            chunks.append(grupo.drop(columns=["__row_id_tmp"]))
            continue

        best = (
            tmp_valid
            .sort_values(["__row_id_tmp", "fecha_inicio", "__source_order", "id_descuento"], ascending=[True, False, True, True])
            .drop_duplicates(subset=["__row_id_tmp"], keep="first")
            [["__row_id_tmp", "monto_descuento", "id_descuento"]]
            .rename(columns={
                "monto_descuento": f"{output_col}__new",
                "id_descuento": f"{output_id_col}__new",
            })
        )

        grupo_out = grupo.merge(best, on="__row_id_tmp", how="left")
        grupo_out[output_col] = grupo_out[output_col].where(grupo_out[output_col].notna(), grupo_out[f"{output_col}__new"])
        grupo_out[output_id_col] = grupo_out[output_id_col].where(grupo_out[output_id_col].notna(), grupo_out[f"{output_id_col}__new"])
        grupo_out = grupo_out.drop(columns=["__row_id_tmp", f"{output_col}__new", f"{output_id_col}__new"])
        chunks.append(grupo_out)

    out = pd.concat(chunks, ignore_index=False).sort_index().reset_index(drop=True)
    out[output_id_col] = out[output_id_col].astype("Int64")
    return out


def _assign_list_discount(ventas_df, descuentos_df, sales_keys, discount_keys, output_col, output_id_col):
    out = ventas_df.copy()
    if output_col not in out.columns:
        out[output_col] = pd.NA
    if output_id_col not in out.columns:
        out[output_id_col] = pd.NA

    lookup = {
        key: sub[["id_descuento", "fecha_inicio", "fecha_fin", "monto_descuento", "__source_order"]].reset_index(drop=True)
        for key, sub in descuentos_df.groupby(discount_keys, sort=False, dropna=False)
    }

    chunks = []
    for key_values, grupo in out.groupby(sales_keys, sort=False, dropna=False):
        if not isinstance(key_values, tuple):
            key_values = (key_values,)

        grupo = grupo.copy()
        grupo["__row_id_tmp"] = grupo.index
        pendientes = grupo[output_col].isna()
        if not pendientes.any():
            chunks.append(grupo.drop(columns=["__row_id_tmp"]))
            continue

        descuentos_sub = lookup.get(tuple(key_values))
        if descuentos_sub is None or descuentos_sub.empty:
            chunks.append(grupo.drop(columns=["__row_id_tmp"]))
            continue

        tmp = grupo.loc[pendientes, ["__row_id_tmp", "Fecha Factura"]].merge(descuentos_sub, how="cross")
        tmp_valid = tmp[
            (tmp["Fecha Factura"] >= tmp["fecha_inicio"]) &
            (tmp["Fecha Factura"] <= tmp["fecha_fin"])
        ]

        if tmp_valid.empty:
            chunks.append(grupo.drop(columns=["__row_id_tmp"]))
            continue

        latest_start = tmp_valid.groupby("__row_id_tmp")["fecha_inicio"].transform("max")
        best = tmp_valid[tmp_valid["fecha_inicio"] == latest_start].copy()
        best = best.sort_values(["__row_id_tmp", "__source_order", "id_descuento"], ascending=[True, True, True])
        best = best.drop_duplicates(subset=["__row_id_tmp", "id_descuento"], keep="first")
        best = (
            best
            .groupby("__row_id_tmp", as_index=False)
            .agg(
                monto_descuento=("monto_descuento", lambda s: [float(x) for x in s.tolist()]),
                id_descuento=("id_descuento", lambda s: [int(x) for x in s.tolist()]),
            )
            .rename(columns={
                "monto_descuento": f"{output_col}__new",
                "id_descuento": f"{output_id_col}__new",
            })
        )

        grupo_out = grupo.merge(best, on="__row_id_tmp", how="left")
        grupo_out[output_col] = grupo_out[output_col].where(grupo_out[output_col].notna(), grupo_out[f"{output_col}__new"])
        grupo_out[output_id_col] = grupo_out[output_id_col].where(grupo_out[output_id_col].notna(), grupo_out[f"{output_id_col}__new"])
        grupo_out = grupo_out.drop(columns=["__row_id_tmp", f"{output_col}__new", f"{output_id_col}__new"])
        chunks.append(grupo_out)

    return pd.concat(chunks, ignore_index=False).sort_index().reset_index(drop=True)


def _assign_single_discount_low_memory(ventas_df, descuentos_df, sales_keys, discount_keys, output_col, output_id_col):
    out = ventas_df.copy()
    if output_col not in out.columns:
        out[output_col] = pd.NA
    if output_id_col not in out.columns:
        out[output_id_col] = pd.NA

    sales_indices = out.groupby(sales_keys, sort=False, dropna=False).indices
    discount_indices = descuentos_df.groupby(discount_keys, sort=False, dropna=False).indices

    for key_values, discount_idx in discount_indices.items():
        if not isinstance(key_values, tuple):
            key_values = (key_values,)

        sales_idx = sales_indices.get(tuple(key_values))
        if sales_idx is None or len(sales_idx) == 0:
            continue

        pendientes = out.loc[sales_idx, output_col].isna()
        if not pendientes.any():
            continue

        descuentos_sub = descuentos_df.iloc[discount_idx][["fecha_inicio", "fecha_fin", "monto_descuento", "id_descuento", "__source_order"]]
        descuentos_sub = descuentos_sub.sort_values(["fecha_inicio", "__source_order", "id_descuento"], ascending=[False, True, True])

        fechas = out.loc[sales_idx, "Fecha Factura"]

        for fecha_inicio, fecha_fin, monto_descuento, id_descuento, _ in descuentos_sub.itertuples(index=False, name=None):
            mask = pendientes & fechas.ge(fecha_inicio) & fechas.le(fecha_fin)
            if mask.any():
                matched_idx = mask.index[mask]
                out.loc[matched_idx, output_col] = monto_descuento
                out.loc[matched_idx, output_id_col] = int(id_descuento)
                pendientes = out.loc[sales_idx, output_col].isna()
                if not pendientes.any():
                    break

    out[output_id_col] = out[output_id_col].astype("Int64")
    return out.sort_index().reset_index(drop=True)


def _split_discount_exact_fallback(descuentos_df):
    exact_mask = descuentos_df["cod_consolidado"].notna() & descuentos_df["cod_consolidado"].ne("")
    return descuentos_df.loc[exact_mask].copy(), descuentos_df.loc[~exact_mask].copy()


merged = merged.drop(
    columns=[
        "dscto_base",
        "id_descuento_base",
        "dscto_volumen",
        "ids_descuento_volumen",
        "dscto_binario",
        "id_descuento_binario",
        "carta_impacto",
        "id_descuento_carta_impacto",
    ],
    errors="ignore",
)
merged["Fecha Factura"] = pd.to_datetime(merged["Fecha Factura"], errors="coerce")
merged["Cod SKU"] = _as_stripped(merged["Cod SKU"])
merged["Cod Canal Comercial"] = _as_stripped(merged["Cod Canal Comercial"])
merged["Cod Consolidado"] = _normalize_consolidado_key(merged["Cod Consolidado"])
merged["Cod Cliente"] = _as_stripped(merged["Cod Cliente"])

dsctos_base = _prepare_discount_frame(
    dsctos_base,
    required_cols=["Material", "C.Comerc."],
    importe_parser=lambda s: pd.to_numeric(s, errors="coerce"),
    tipo_descuento="base",
    rename_map={
        "Material": "cod_sku",
        "C.Comerc.": "cod_canal",
        "G.Cadenas": "cod_consolidado",
        "Válido de ": "fecha_inicio",
        "A         ": "fecha_fin",
        "Importe": "monto_descuento",
    },
    blank_allowed_cols=["G.Cadenas"],
)
dsctos_volumen = _prepare_discount_frame(
    dsctos_volumen,
    required_cols=["Material", "C.Comerc."],
    importe_parser=_parse_signed_discount,
    tipo_descuento="volumen",
    rename_map={
        "Material": "cod_sku",
        "C.Comerc.": "cod_canal",
        "G.Cadenas": "cod_consolidado",
        "Válido de ": "fecha_inicio",
        "A         ": "fecha_fin",
        "Importe": "monto_descuento",
    },
    blank_allowed_cols=["G.Cadenas"],
)
dsctos_binario = _prepare_discount_frame(
    dsctos_binario,
    required_cols=["Material", "C.Comerc."],
    importe_parser=_parse_signed_discount,
    tipo_descuento="binario",
    rename_map={
        "Material": "cod_sku",
        "C.Comerc.": "cod_canal",
        "G.Cadenas": "cod_consolidado",
        "Válido de ": "fecha_inicio",
        "A         ": "fecha_fin",
        "Importe": "monto_descuento",
    },
    blank_allowed_cols=["G.Cadenas"],
)
carta_impacto = _prepare_discount_frame(
    carta_impacto,
    required_cols=["Material", "Cliente"],
    importe_parser=lambda s: pd.to_numeric(s, errors="coerce"),
    tipo_descuento="carta_impacto",
    rename_map={
        "Material": "cod_sku",
        "Cliente": "cod_cliente",
        "Válido de ": "fecha_inicio",
        "A         ": "fecha_fin",
        "Importe": "monto_descuento",
    },
)

consolidado_descuentos = pd.concat(
    [dsctos_base, dsctos_volumen, dsctos_binario, carta_impacto],
    ignore_index=True,
)
consolidado_descuentos = consolidado_descuentos.sort_values(
    [
        "tipo_descuento",
        "cod_sku",
        "cod_canal",
        "cod_consolidado",
        "cod_cliente",
        "fecha_inicio",
        "fecha_fin",
        "monto_descuento",
        "__source_order",
    ],
    kind="stable",
    na_position="last",
).reset_index(drop=True)
consolidado_descuentos["id_descuento"] = np.arange(1, len(consolidado_descuentos) + 1, dtype=np.int64)
consolidado_descuentos = consolidado_descuentos[[
    "id_descuento",
    "tipo_descuento",
    "cod_sku",
    "cod_canal",
    "cod_consolidado",
    "cod_cliente",
    "fecha_inicio",
    "fecha_fin",
    "monto_descuento",
    "__source_order",
]]

output_path_descuentos = "datos/Descuentos históricos/consolidado_descuentos.csv"
consolidado_descuentos.drop(columns=["__source_order"])

dsctos_base = consolidado_descuentos[consolidado_descuentos["tipo_descuento"] == "base"].copy()
dsctos_volumen = consolidado_descuentos[consolidado_descuentos["tipo_descuento"] == "volumen"].copy()
dsctos_binario = consolidado_descuentos[consolidado_descuentos["tipo_descuento"] == "binario"].copy()
carta_impacto = consolidado_descuentos[consolidado_descuentos["tipo_descuento"] == "carta_impacto"].copy()

dsctos_base_exact, dsctos_base_fallback = _split_discount_exact_fallback(dsctos_base)
dsctos_volumen_exact, dsctos_volumen_fallback = _split_discount_exact_fallback(dsctos_volumen)
dsctos_binario_exact, dsctos_binario_fallback = _split_discount_exact_fallback(dsctos_binario)

merged = _assign_single_discount_low_memory(
    merged,
    dsctos_base_exact,
    sales_keys=["Cod SKU", "Cod Canal Comercial", "Cod Consolidado"],
    discount_keys=["cod_sku", "cod_canal", "cod_consolidado"],
    output_col="dscto_base",
    output_id_col="id_descuento_base",
)
merged = _assign_single_discount_low_memory(
    merged,
    dsctos_base_fallback,
    sales_keys=["Cod SKU", "Cod Canal Comercial"],
    discount_keys=["cod_sku", "cod_canal"],
    output_col="dscto_base",
    output_id_col="id_descuento_base",
)
merged = _assign_list_discount(
    merged,
    dsctos_volumen_exact,
    sales_keys=["Cod SKU", "Cod Canal Comercial", "Cod Consolidado"],
    discount_keys=["cod_sku", "cod_canal", "cod_consolidado"],
    output_col="dscto_volumen",
    output_id_col="ids_descuento_volumen",
)
merged = _assign_list_discount(
    merged,
    dsctos_volumen_fallback,
    sales_keys=["Cod SKU", "Cod Canal Comercial"],
    discount_keys=["cod_sku", "cod_canal"],
    output_col="dscto_volumen",
    output_id_col="ids_descuento_volumen",
)
merged = _assign_single_discount_low_memory(
    merged,
    dsctos_binario_exact,
    sales_keys=["Cod SKU", "Cod Canal Comercial", "Cod Consolidado"],
    discount_keys=["cod_sku", "cod_canal", "cod_consolidado"],
    output_col="dscto_binario",
    output_id_col="id_descuento_binario",
)
merged = _assign_single_discount_low_memory(
    merged,
    dsctos_binario_fallback,
    sales_keys=["Cod SKU", "Cod Canal Comercial"],
    discount_keys=["cod_sku", "cod_canal"],
    output_col="dscto_binario",
    output_id_col="id_descuento_binario",
)
merged = _assign_single_discount_low_memory(
    merged,
    carta_impacto,
    sales_keys=["Cod SKU", "Cod Cliente"],
    discount_keys=["cod_sku", "cod_cliente"],
    output_col="carta_impacto",
    output_id_col="id_descuento_carta_impacto",
)

print(f"Tabla consolidada de descuentos guardada en: {output_path_descuentos}")
print(f"Total descuentos consolidados: {len(consolidado_descuentos):,}")
print(f"dscto_base asignado: {merged['dscto_base'].notna().sum():,}")
print(f"dscto_volumen asignado: {merged['dscto_volumen'].notna().sum():,}")
print(f"dscto_binario asignado: {merged['dscto_binario'].notna().sum():,}")
print(f"carta_impacto asignado: {merged['carta_impacto'].notna().sum():,}")

cols_muestra_dsctos = [
    "Fecha Factura",
    "Cod SKU",
    "Cod Canal Comercial",
    "Cod Consolidado",
    "Cod Cliente",
    "dscto_base",
    "id_descuento_base",
    "dscto_volumen",
    "ids_descuento_volumen",
    "dscto_binario",
    "id_descuento_binario",
    "carta_impacto",
    "id_descuento_carta_impacto",
]
merged.loc[
    merged[[
        "id_descuento_base",
        "ids_descuento_volumen",
        "id_descuento_binario",
        "id_descuento_carta_impacto",
    ]].notna().any(axis=1),
    cols_muestra_dsctos,
].head()

Tabla consolidada de descuentos guardada en: datos/Descuentos históricos/consolidado_descuentos.csv
Total descuentos consolidados: 76,509
dscto_base asignado: 1,332,116
dscto_volumen asignado: 1,008,870
dscto_binario asignado: 2,033,413
carta_impacto asignado: 2,231

,Fecha Factura,Cod SKU,Cod Canal Comercial,Cod Consolidado,Cod Cliente,dscto_base,id_descuento_base,dscto_volumen,ids_descuento_volumen,dscto_binario,id_descuento_binario,carta_impacto,id_descuento_carta_impacto
1,2025-01-03,399,HR,55,43790,-3.0,2352,NaN,NaN,<NA>,<NA>,<NA>,<NA>
3,2025-01-02,3991,CB,32,1174760,-12.5,2372,NaN,NaN,<NA>,<NA>,<NA>,<NA>
7,2025-01-02,6800,CB,54,1137411,-3.0,2837,NaN,NaN,<NA>,<NA>,<NA>,<NA>
10,2025-01-02,3144,CB,54,1114635,-3.0,1277,NaN,NaN,<NA>,<NA>,<NA>,<NA>
11,2025-01-02,3142,CB,54,1200313,-3.0,1262,NaN,NaN,<NA>,<NA>,<NA>,<NA>

In [31]:
# Vista rápida de la tabla consolidada de descuentos
consolidado_descuentos.drop(columns=["__source_order"]).head()

,id_descuento,tipo_descuento,cod_sku,cod_canal,cod_consolidado,cod_cliente,fecha_inicio,fecha_fin,monto_descuento
0,1,base,1006,CB,54,<NA>,2026-03-02,2026-03-18,0.0
1,2,base,1006,CB,54,<NA>,2026-03-19,9999-12-31,0.0
2,3,base,1006,HR,55,<NA>,2026-03-02,2026-03-18,0.0
3,4,base,1006,HR,55,<NA>,2026-03-19,2026-03-29,0.0
4,5,base,1006,HR,56,<NA>,2023-11-01,2024-06-09,-24.8

In [32]:
merged.to_csv("datos/Ventas por Cliente/ventas_con_precio_lista_y_descuentos_2025_2026.csv", index=False)

In [33]:
consolidado_descuentos.to_csv("datos/Descuentos históricos/consolidado_descuentos.csv", index=False)