In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
# Cargar datos
# path_ventas = "datos/Ventas por Cliente/ventas_con_precio_lista_y_descuentos_2025_2026.csv"
path_ventas = "datos/Ventas por Cliente/ventas_2025_2026.csv"
ventas = pd.read_csv(path_ventas)
print("Ventas - Filas:", ventas.shape[0])
ventas.head()

/var/folders/dw/9r647bwd1kl_g5lxtz0kh4100000gp/T/ipykernel_32486/4116466136.py:4: DtypeWarning: Columns (0: Cod Canal Comercial) have mixed types. Specify dtype option on import or set low_memory=False.
  ventas = pd.read_csv(path_ventas)

Ventas - Filas: 10596574

,Año,Mes,Cod Canal Comercial,Clase Factura,Fecha Factura,Cod Cliente,Nombre Cliente Padre,Cod Consolidado,Nombre Consolidado,Nombre Familia,...,Nombre Tipo Carne,Cod SKU,Nombre SKU,Factura Venta,Factura Kilos,Kilo Real,Kilos Nc,Monto Nc,Monto Real,Precio
0,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,SALAMES,...,CERDO,3034,SALAME 10x100 GR LP,43440,4.0,4.0,NaN,NaN,43440,10860.000000
1,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,MORTADELAS,...,CERDO,3049,MORTADELA JAMONADA LP 150 G.,17919,3.3,3.3,NaN,NaN,17919,5430.000000
2,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,PATE,...,CERDO,3080,PATE TEEWURST 16x125 GR LP,23888,4.0,4.0,NaN,NaN,23888,5972.000000
3,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,JAMON G1,...,CERDO,3108,JAMON PIERNA CP 8x250 GR LP,48869,6.0,6.0,NaN,NaN,48869,8144.833333
4,2025,1,CB,ZV01,20250102,1145633,NaN,32,COBERTURA,PATE,...,POLLO,3148,PASTA POLLO PIMENTON 8x125 GR LP,4887,1.0,1.0,NaN,NaN,4887,4887.000000

In [3]:
ventas.columns

Index(['Año', 'Mes', 'Cod Canal Comercial', 'Clase Factura', 'Fecha Factura',
       'Cod Cliente', 'Nombre Cliente Padre', 'Cod Consolidado',
       'Nombre Consolidado', 'Nombre Familia', 'N° Factura', 'Nombre Marca',
       'Nombre Tipo Carne', 'Cod SKU', 'Nombre SKU', 'Factura Venta',
       'Factura Kilos', 'Kilo Real', 'Kilos Nc', 'Monto Nc', 'Monto Real',
       'Precio'],
      dtype='str')

In [4]:
# path_info_zonales = "datos/Clientes - Zonales.xlsx"
path_info_zonales = "Cliente Zonal anual.xlsx"
zonales = pd.read_excel(path_info_zonales)
zonales.head()

       REGIONES  Id cliente
0      SANTIAGO     1182447
1      SANTIAGO     1167739
2  SAN FERNANDO       51007
3  VIÑA DEL MAR      525521
4         ARICA      547235

In [5]:
zonales.groupby("Id cliente").agg({
    "REGIONES": "nunique"
}).max()

REGIONES    1
dtype: int64

In [6]:
zonales.columns

Index(['REGIONES', 'Id cliente'], dtype='str')

In [7]:
mapeo_cliente_zonal = dict(zip(zonales['Id cliente'], zonales['REGIONES']))

In [8]:
## Filtrar solo los canales relevantes
canales_relevantes = [
    "COBERTURA",
    "VOLUMEN COBERTURA",
    # "MAYORISTAS CADENAS",
    # "MAYORISTA B VOLUMEN",
    # "OTROS MAYORISTAS",
    # "HORECA VOLUMEN",
    # "OTROS HORECA",
]
ventas = ventas[ventas["Nombre Consolidado"].isin(canales_relevantes)]
print("Ventas después de filtrar canales irrelevantes - Filas:", ventas.shape[0])

ventas = ventas[
    ((ventas["Año"] == 2025) & (ventas["Mes"] >= 10)) |
    (ventas["Año"] == 2026)
]
print("Ventas después de filtrar fechas - Filas:", ventas.shape[0])
ventas.head()

Ventas después de filtrar canales irrelevantes - Filas: 9616513
Ventas después de filtrar fechas - Filas: 3891188

,Año,Mes,Cod Canal Comercial,Clase Factura,Fecha Factura,Cod Cliente,Nombre Cliente Padre,Cod Consolidado,Nombre Consolidado,Nombre Familia,...,Nombre Tipo Carne,Cod SKU,Nombre SKU,Factura Venta,Factura Kilos,Kilo Real,Kilos Nc,Monto Nc,Monto Real,Precio
6307580,2025,10,CB,ZV01,20251001,1170656,NaN,32,COBERTURA,MORTADELAS,...,CERDO,403,MORTADELA LISA MINI PZA 8X400 GR SJ,7498,3.2,3.2,0.0,0.0,7498,2343.125000
6307581,2025,10,CB,ZV01,20251001,1170656,NaN,32,COBERTURA,MORTADELAS,...,CERDO,1402,MORTADELA LISA 250 GRS.SJ,11246,3.0,3.0,0.0,0.0,11246,3748.666667
6307582,2025,10,CB,ZV01,20251001,1170656,NaN,32,COBERTURA,TOCINOS,...,CERDO,3960,TOCINO 10x100 GR LP,12281,1.0,1.0,0.0,0.0,12281,12281.000000
6307583,2025,10,CB,ZV01,20251001,1139880,NaN,32,COBERTURA,PATE,...,VACUNO,421,PATE TERNERA 8x125 GRS.SJ,3878,1.0,1.0,0.0,0.0,3878,3878.000000
6307584,2025,10,CB,ZV01,20251001,1139880,NaN,32,COBERTURA,HORTALIZAS,...,OTROS,2710,MIX PRIMAVERA POROTO VERDE 10X200 GR SJ,5494,2.0,2.0,0.0,0.0,5494,2747.000000

In [9]:
# año mes en formato oct-25
ventas["Año2"] = ventas["Año"].map({2025:25, 2026:26})
ventas["Mes2"] = ventas["Mes"].map({
    10: "oct",
    11: "nov",
    12: "dic",
    1:  "ene",
    2:  "feb",
    3:  "mar"
})
ventas["año_mes"] = ventas["Mes2"].astype(str) + "-" + ventas["Año2"].astype(str)

In [10]:
mapeo_cliente_consolidado = dict(zip(ventas['Cod Cliente'], ventas['Nombre Consolidado']))

In [11]:
base_ventas_para_costeo = ventas.groupby([
    "año_mes",
    "Cod Cliente",
    "Cod SKU"
]).agg({
    "Kilo Real": "sum",
    "Monto Real": "sum",
}).reset_index(
).rename(columns={
    "Cod Cliente": "cod_cliente",
    "Cod SKU": "cod_sku",
    "Kilo Real": "kg_totales",
    "Monto Real": "facturacion",
})

base_ventas_para_costeo["zonal"] = base_ventas_para_costeo["cod_cliente"].map(mapeo_cliente_zonal)
base_ventas_para_costeo["consolidado"] = base_ventas_para_costeo["cod_cliente"].map(mapeo_cliente_consolidado)

base_ventas_para_costeo.head()

  año_mes  cod_cliente  cod_sku  kg_totales  facturacion     zonal consolidado
0  dic-25          235       20       2.775        13631  SANTIAGO   COBERTURA
1  dic-25          235       30       1.468         7211  SANTIAGO   COBERTURA
2  dic-25          235     6770       4.000        26988  SANTIAGO   COBERTURA
3  dic-25          235     8508       1.600         6412  SANTIAGO   COBERTURA
4  dic-25          499     3032       5.000        25854  SANTIAGO   COBERTURA

In [12]:
base_ventas_para_costeo = base_ventas_para_costeo[[
    "año_mes",
    "cod_cliente",
    "zonal",
    "consolidado",
    "cod_sku",
    "kg_totales",
    "facturacion"
]]

base_ventas_para_costeo.head()

  año_mes  cod_cliente     zonal consolidado  cod_sku  kg_totales  facturacion
0  dic-25          235  SANTIAGO   COBERTURA       20       2.775        13631
1  dic-25          235  SANTIAGO   COBERTURA       30       1.468         7211
2  dic-25          235  SANTIAGO   COBERTURA     6770       4.000        26988
3  dic-25          235  SANTIAGO   COBERTURA     8508       1.600         6412
4  dic-25          499  SANTIAGO   COBERTURA     3032       5.000        25854

In [13]:
len(base_ventas_para_costeo["cod_cliente"].unique())

38368

In [14]:
len(base_ventas_para_costeo[
    base_ventas_para_costeo["zonal"].isna()
]["cod_cliente"].unique())

111

In [15]:
base_ventas_para_costeo["zonal"].value_counts()

zonal
SANTIAGO        748214
SAN FERNANDO    161151
VIÑA DEL MAR    139483
LA SERENA       123744
CONCEPCION      113820
TEMUCO          105415
RANCAGUA         92058
CHILLAN          87119
TALCA            75930
ANTOFAGASTA      70953
OSORNO           67662
LOS ANGELES      63185
IQUIQUE          59801
COPIAPO          53877
SAN FELIPE       46202
PUERTO MONTT     44407
CALAMA           44143
ARICA            43040
                 22284
PUNTA ARENAS     21871
COYHAYQUE        11010
Name: count, dtype: int64

In [16]:
base_ventas_para_costeo.head()

  año_mes  cod_cliente     zonal consolidado  cod_sku  kg_totales  facturacion
0  dic-25          235  SANTIAGO   COBERTURA       20       2.775        13631
1  dic-25          235  SANTIAGO   COBERTURA       30       1.468         7211
2  dic-25          235  SANTIAGO   COBERTURA     6770       4.000        26988
3  dic-25          235  SANTIAGO   COBERTURA     8508       1.600         6412
4  dic-25          499  SANTIAGO   COBERTURA     3032       5.000        25854

In [17]:
# base_ventas_para_costeo.to_csv("datos/ventas_para_costeo.csv")

In [18]:
base_ventas_para_costeo[base_ventas_para_costeo["cod_cliente"]==256330]

,año_mes,cod_cliente,zonal,consolidado,cod_sku,kg_totales,facturacion
19766,dic-25,256330,VIÑA DEL MAR,COBERTURA,20,5.88,28888
19767,dic-25,256330,VIÑA DEL MAR,COBERTURA,265,15.00,56235
19768,dic-25,256330,VIÑA DEL MAR,COBERTURA,421,4.00,15512
19769,dic-25,256330,VIÑA DEL MAR,COBERTURA,689,3.70,13187
19770,dic-25,256330,VIÑA DEL MAR,COBERTURA,710,4.32,15824
...,...,...,...,...,...,...,...
1840842,oct-25,256330,VIÑA DEL MAR,COBERTURA,8300,23.20,149964
1840843,oct-25,256330,VIÑA DEL MAR,COBERTURA,8451,88.00,216128
1840844,oct-25,256330,VIÑA DEL MAR,COBERTURA,8454,192.00,434303
1840845,oct-25,256330,VIÑA DEL MAR,COBERTURA,8508,24.00,94908
1840846,oct-25,256330,VIÑA DEL MAR,COBERTURA,8798,73.50,285030